export const ACTIVITY_LOG_ACTIONS = {
  ADD_TRAINING_POINTS: 'add_training_points',
  APPROVE_TRAINING: 'approve_training',
  AWARD: 'award',
  CONSUME_DRACHMA: 'consume_drachma',
  CONSUME_ITEM: 'consume_item',
  DEDUCT: 'deduct',
  DEDUCT_TRAINING_POINTS: 'deduct_training_points',
  EARN_DRACHMA: 'earn_drachma',
  GIVE_ITEM: 'give_item',
  HARVEST_APPROVED: 'harvest_approved',
  MISSION_APPROVED: 'mission_approved',
  RECEIVE_ITEM: 'receive_item',
  REJECT_TRAINING: 'reject_training',
  SHOP_PURCHASE: 'shop_purchase',
  SKILL_UPGRADE: 'skill_upgrade',
  SPEND_DRACHMA: 'spend_drachma',
  SPEND_TRAINING_POINTS_UPGRADE: 'spend_training_points_upgrade',
  STAT_REFUND: 'stat_refund',
  STAT_UPGRADE: 'stat_upgrade',
  TASK_APPROVED: 'task_approved',
  TRAINING_APPROVED: 'training_approved',
  TRANSFER_ITEM: 'transfer_item',
  UPDATE_ITEM_STATE: 'update_item_state',
  WISH_RECEIVED: 'wish_received',
  WISH_TOSSED: 'wish_tossed',
}