export const ACTIVITY_LOG_CATEGORY = {
  DRACHMA: 'drachma',
  ITEM: 'item',
  EQUIPMENT: 'equipment',
  STAT: 'stat',
  ACTION: 'action',
} as const;

export const ACTIVITY_LOG_ACTIONS = {
  ADD_TRAINING_POINTS: 'add_training_points',
  APPROVE_TRAINING: 'approve_training',
  APPROVE_BIG_HOUSE_ROLEPLAY: 'approve_big_house',
  AWARD: 'award',
  CONSUME_DRACHMA: 'consume_drachma',
  CONSUME_ITEM: 'consume_item',
  DEDUCT: 'deduct',
  DEDUCT_TRAINING_POINTS: 'deduct_training_points',
  EARN_DRACHMA: 'earn_drachma',
  GIVE_ITEM: 'give_item',
  HARVEST_APPROVED: 'harvest_approved',
  MISSION_APPROVED: 'mission_approved',
  RECEIVE_ITEM: 'receive_item',
  REJECT_TRAINING: 'reject_training',
  REJECT_BIG_HOUSE_ROLEPLAY: 'reject_big_house',
  REJECT_HARVEST: 'reject_harvest',
  SHOP_PURCHASE: 'shop_purchase',
  SKILL_UPGRADE: 'skill_upgrade',
  SPEND_DRACHMA: 'spend_drachma',
  SPEND_TRAINING_POINTS_UPGRADE: 'spend_training_points_upgrade',
  STAT_REFUND: 'stat_refund',
  STAT_UPGRADE: 'stat_upgrade',
  TASK_APPROVED: 'task_approved',
  TRAINING_APPROVED: 'training_approved',
  TRANSFER_ITEM: 'transfer_item',
  UPDATE_ITEM_STATE: 'update_item_state',
  WISH_RECEIVED: 'wish_received',
  WISH_TOSSED: 'wish_tossed',
  EQUIPMENT_UPGRADE: 'equipment_upgrade',
}

export const ACTIVITY_LOG_SOURCES = {
  ADMIN: 'admin',
  ADMIN_PLAYER_INVENTORY: 'admin_player_inventory',
  ADMIN_PLAYER_INVENTORY_ADD: 'admin_player_inventory_add',
  ADMIN_PLAYER_INVENTORY_BULK: 'admin_player_inventory_bulk',
  ADMIN_PLAYER_INVENTORY_BULK_ADD: 'admin_player_inventory_bulk_add',
  ADMIN_TRAINING_APPROVAL: 'admin_training_approval',
  ADMIN_TRAINING_APPROVAL_ATHENA_BONUS: 'admin_training_approval_athena_bonus',
  BIG_HOUSE: 'big_house',
  BIG_HOUSE_APPROVAL: 'big_house_approval',
  CASHIER: 'cashier',
  CONSUME_MULTIPLE_ITEMS: 'consume_multiple_items',
  DAILY_GIFT: 'daily_gift',
  FORGE: 'forge',
  HARVEST: 'harvest',
  HARVEST_APPROVAL: 'harvest_approval',
  HARVEST_GARDENING_SET_USED: 'harvest_gardening_set_used',
  HERMES_PURSE: 'hermes_purse',
  HERMES_PURSE_TRACKING: 'hermes_purse_tracking',
  HERMES_PURSE_BONUS: 'hermes_purse_bonus',
  IRIS_FOUNTAIN: 'iris_fountain',
  IRIS_WISH: 'iris_wish',
  IRIS_WISH_BONUS: 'iris_wish_bonus',
  IRIS_WISH_HECATE: 'iris_wish_hecate',
  IRIS_WISH_HEBE: 'iris_wish_hebe',
  IRIS_WISH_HERMES: 'iris_wish_hermes',
  IRIS_KEYCHAIN_BONUS: 'iris_keychain_bonus',
  NIKE_STATUE: 'nike_statue',
  NIKE_WISH_BATTLE_BONUS: 'nike_wish_battle_bonus',
  PLAYER_INVENTORY: 'player_inventory',
  PLAYER_INVENTORY_BULK: 'player_inventory_bulk',
  SHOP: 'shop',
  SHOP_DISCOUNT_USED: 'shop_discount_used',
  STATS_REFUND_ALL: 'stats_refund_all',
  STATS_USE_CODEX: 'stats_use_codex',
  TRAINING_GROUNDS: 'training_grounds',
  TRAINING_ROLEPLAY_REFUND: 'training_roleplay_refund',
  TRAINING_ROLEPLAY_SKIP: 'training_roleplay_skip',
  TRANSFER_ITEM: 'transfer_item',
  TREASURY_TRANSFER: 'treasury_transfer',
  TREASURY_TRANSFER_ROLLBACK: 'treasury_transfer_rollback',
  FORGE_RECEIVE: 'forge_receive',
  UNKNOWN: 'unknown',
  ITEM_STATE_UPDATE: 'item_state_update',
  SYSTEM: 'system',
} as const;

export const SOURCE_LABELS: Record<string, string> = {
  admin_player_inventory_add: 'Added by admin',
  admin_player_inventory_bulk_add: 'Added by admin',
  admin_player_inventory: 'Removed by admin',
  admin_player_inventory_bulk: 'Removed by admin',
  admin_training_approval: 'Training approval',
  admin_training_approval_athena_bonus: 'Athena blessing',
  big_house_approval: 'Big House approval',
  cashier: 'the Shop',
  consume_multiple_items: 'multiple item use',
  daily_gift: 'Daily Gift',
  forge_receive: 'the Forge',
  forge_upgrade: 'a Forge upgrade',
  harvest_approval: 'Harvest approval',
  hermes_purse_bonus: 'Hermes Purse bonus',
  hermes_purse_tracking: 'Hermes Purse tracking',
  iris_fountain: 'Rainbow Drachma after the Wish of Iris',
  iris_wish: 'the Wish of Iris',
  iris_wish_hecate: 'the Wish of Hecate',
  iris_keychain_bonus: 'Iris Keychain bonus',
  nike_statue: "Nike's Statue",
  nike_wish_battle_bonus: 'Nike Wish',
  player_inventory: 'Removed by admin',
  player_inventory_bulk: 'Removed by admin',
  shop: 'the Shop',
  shop_discount_used: 'a shop discount ticket',
  stats_refund_all: 'a full stat refund',
  stats_use_codex: "Athena's Codex",
  training_grounds: 'Training Grounds',
  training_roleplay_refund: 'training roleplay refund',
  training_roleplay_skip: 'training roleplay skip',
  transfer_item_destination: 'an item transfer',
  transfer_item_source: 'an item transfer',
  transfer_item_rollback: 'an item transfer rollback',
  treasury_transfer: 'Camp Treasury transfer',
  treasury_transfer_rollback: 'Camp Treasury transfer rollback',
  unknown: 'an unknown source',
};
