export const ACTIVITY_LOG_ACTIONS = {
  ADD_TRAINING_POINTS: 'add_training_points',
  APPROVE_TRAINING: 'approve_training',
  AWARD: 'award',
  CONSUME_DRACHMA: 'consume_drachma',
  CONSUME_ITEM: 'consume_item',
  DEDUCT: 'deduct',
  DEDUCT_TRAINING_POINTS: 'deduct_training_points',
  EARN_DRACHMA: 'earn_drachma',
  GIVE_ITEM: 'give_item',
  HARVEST_APPROVED: 'harvest_approved',
  MISSION_APPROVED: 'mission_approved',
  RECEIVE_ITEM: 'receive_item',
  REJECT_TRAINING: 'reject_training',
  SHOP_PURCHASE: 'shop_purchase',
  SKILL_UPGRADE: 'skill_upgrade',
  SPEND_DRACHMA: 'spend_drachma',
  SPEND_TRAINING_POINTS_UPGRADE: 'spend_training_points_upgrade',
  STAT_REFUND: 'stat_refund',
  STAT_UPGRADE: 'stat_upgrade',
  TASK_APPROVED: 'task_approved',
  TRAINING_APPROVED: 'training_approved',
  TRANSFER_ITEM: 'transfer_item',
  UPDATE_ITEM_STATE: 'update_item_state',
  WISH_RECEIVED: 'wish_received',
  WISH_TOSSED: 'wish_tossed',
}

export const SOURCE_LABELS: Record<string, string> = {
  admin_player_inventory_add: 'Added by admin',
  admin_player_inventory_bulk_add: 'Added by admin',
  admin_player_inventory: 'Removed by admin',
  admin_player_inventory_bulk: 'Removed by admin',
  admin_training_approval: 'Training approval',
  admin_training_approval_athena_bonus: 'Athena blessing',
  big_house_approval: 'Big House approval',
  cashier: 'the Shop',
  consume_multiple_items: 'multiple item use',
  daily_gift: 'Daily Gift',
  forge_receive: 'the Forge',
  forge_upgrade: 'a Forge upgrade',
  harvest_approval: 'Harvest approval',
  hermes_purse_bonus: 'Hermes Purse bonus',
  hermes_purse_tracking: 'Hermes Purse tracking',
  iris_fountain: 'Rainbow Drachma after the Wish of Iris',
  iris_wish: 'the Wish of Iris',
  iris_wish_hecate: 'the Wish of Hecate',
  nike_statue: "Nike's Statue",
  nike_wish_battle_bonus: 'Nike Wish',
  player_inventory: 'Removed by admin',
  player_inventory_bulk: 'Removed by admin',
  shop: 'the Shop',
  shop_discount_used: 'a shop discount ticket',
  stats_refund_all: 'a full stat refund',
  stats_use_codex: "Athena's Codex",
  training_grounds: 'Training Grounds',
  training_roleplay_refund: 'training roleplay refund',
  training_roleplay_skip: 'training roleplay skip',
  transfer_item_destination: 'an item transfer',
  transfer_item_source: 'an item transfer',
  transfer_item_rollback: 'an item transfer rollback',
  treasury_transfer: 'Camp Treasury transfer',
  treasury_transfer_rollback: 'Camp Treasury transfer rollback',
  unknown: 'an unknown source',
};